apiVersion: v1
kind: Service
metadata:
  name: sagemath-service
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  externalIPs:
    - 10.11.12.13
