apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nr-service-endpointslice
  labels:
    kubernetes.io/service-name: nr-service
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8000
endpoints:
  - addresses:
      - "10.11.12.13"
